# Generated by Django 5.0.4 on 2024-05-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_colorvariant_sizevariant_product_color_variant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorvariant',
            old_name='color',
            new_name='color_name',
        ),
    ]
